---
services:
  samba:
    image: elswork/samba
    container_name: samba
    environment:
      TZ: 'Asia/Kolkata'
    ports:
      - "139:139"
      - "445:445"
    restart: unless-stopped
    volumes:
      - /media/segateHdd:/share/folder
    command: '-u "0:0:root:root:toor" -s "SmbShare:/share/folder:ro:root"'
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    labels:
      - 'kopia_backup'

networks:
  default:
