---
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Kolkata
    ports:
      - 5055:5055
    volumes:
      - /opt/jellyseer/config:/app/config
    restart: unless-stopped
    labels:
      - 'kopia_backup'
      - 'com.centurylinklabs.watchtower.enable=true'
