---
services:
  vscode:
    image: gitpod/openvscode-server
    container_name: vscode
    volumes:
      - /opt/vscode/config:/home/workspace:cached
      - ./assets:/config/homer:rw
    ports:
      - 1337:3000
    labels:
      - 'kopia_backup'
      - 'com.centurylinklabs.watchtower.enable=true'
