---
services:
  adguard-home:
    image: adguard/adguardhome:latest
    container_name: adguard-home
    restart: unless-stopped
    volumes:
      - '/opt/adguard-home/work:/opt/adguardhome/work'
      - '/opt/adguard-home/conf:/opt/adguardhome/conf'
    ports:
      - '192.168.1.6:53:53/tcp' # DNS
      - '192.168.1.6:53:53/udp' # DNS
      - '67:67/udp' # for using as a DHCP server
      - '68:68/udp' # for using as a DHCP server
      - '9000:80/tcp' # Admin panel and DNS over HTTPS
      - '3000:3000/tcp' # Admin panel and DNS over HTTPS
      - '853:853/tcp' # DNS over TLS
      # - '784:784/udp' # use as a DNS-over-QUIC
      # - '853:853/udp' # use as a DNS-over-QUIC
      # - '8853:8853/udp' # use as a DNS-over-QUIC
      # - '5443:5443/tcp' # DNSCrypt Server
      # - '5443:5443/udp' # DNSCrypt Server
    cap_add:
      - NET_ADMIN
    labels:
      - 'kopia_backup'
      - 'com.centurylinklabs.watchtower.enable=true'
