---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    environment:
      - PUID=2002
      - PGID=2003
      - TZ=Asia/Kolkata
      - JELLYFIN_PublishedServerUrl=192.168.1.6
      # - HEALTHCHECK_URL="http://localhost:8096/health"
    volumes:
      - /opt/jellyfin/server:/config
      - /media/externalHdd/Movies:/data/movies
      - /media/externalHdd/Series:/data/tvshows
      - /media/externalHdd/Pictures:/data/pictures
      # - /media/externalHdd/TwitchStreams:/data/videos/twitch
      - /media/externalHdd/niflheim/tubearchivist/media:/data/tubearchivist
      - /media/externalHdd/niflheim/metube/downloads:/data/youtube
      - /media/externalHdd/niflheim/additionalMedia:/data/otherVideos
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-fs",
          "-S",
          "--max-time",
          "2",
          "http://localhost:8096/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 8096:8096
      - 8920:8920
      # Optional -> Open for discovery
      - 7359:7359/udp
      - 1900:1900/udp
    restart: always
    labels:
      - "kopia_backup"
      - "com.centurylinklabs.watchtower.enable=true"
