tunnel: tunnel-id
originRequest: # Top-level configuration
    connectTimeout: 30s
    noTLSVerify: true
warp-routing:
    enabled: true

ingress:
    # The localhost:8000 service inherits all root-level configuration.
    # In other words, it will use a connectTimeout of 30 seconds.

    - hostname: sshing.domain.tld
      service: ssh://192.168.x.x:22
    - hostname: dashboard.domain.tld
      service: http://192.168.x.x:8080
    - hostname: portainer.domain.tld
      service: https://192.168.x.x:9443
    - hostname: jellyfin.domain.tld
      service: http://192.168.x.x:8096
    - hostname: uptime.domain.tld
      service: http://192.168.x.x:3001
    # Some built-in services such as `http_status` do not use any configuration.
    # The service below will simply respond with HTTP 404.
    - service: http_status:404
# https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/local/local-management/configuration-file/#naming-and-storing-a-configuration-file
