---
version: '3'
services:
  portainer_api:
    container_name: portainer_api
    build: .
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
      - /opt/portainer_api/containers.json:/opt/portainer_api/containers.json
