---
services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes:
      - /opt/uptime-kuma/data:/app/data
    ports:
      - 3001:3001
    dns: 192.168.1.6
    restart: always
    security_opt:
      - no-new-privileges:true
    labels:
      - 'kopia_backup'
      - 'com.centurylinklabs.watchtower.enable=true'
