---
version: "3.1"

services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: server-name
    environment:
      - PUID=2002
      - PGID=2003
      - TZ=Asia/Kolkata
    volumes:
      - /opt/syncthing/config:/config
      # - /opt/backup:/opt/backup
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    restart: always
    security_opt:
      - no-new-privileges:true
    labels:
      - 'kopia_backup'
      - 'com.centurylinklabs.watchtower.enable=true'
